name: Push Github Private NPM Registry

on: release

jobs:
  publish:
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/build_and_publish_npm_package.yml@master
    secrets:
      DEVOPS_READ_PACKAGE_TOKEN: ${{ secrets.DEVOPS_READ_PACKAGE_TOKEN }}
  notify:
    needs: publish
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/notify_slack.yml@master
    secrets:
      CP_SLACK_CHANNEL_RG_CRYPTO: ${{ secrets.CP_SLACK_CHANNEL_RG_CRYPTO }}
      