name: Push Github Private NPM Registry

on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/build_and_publish_official_public_npm_package.yml@CW-21443_Update-Nodejs
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  notify:
    needs: publish
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/notify_slack.yml@CW-21443_Update-Nodejs
    secrets:
      CP_SLACK_CHANNEL_RG_CRYPTO: ${{ secrets.CP_SLACK_CHANNEL_RG_CRYPTO }}
