name: Push Github Private NPM Registry

on:
  push:
    branches:
      - master
      - feat/CW-29077

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/build_and_publish_official_public_npm_package_oidc.yml@feat/CW-29077-add-oidc
  notify:
    needs: publish
    uses: CoolBitX-Technology/cp-workflow-template/.github/workflows/notify_slack.yml@master
    secrets:
      CP_SLACK_CHANNEL_RG_CRYPTO: ${{ secrets.CP_SLACK_CHANNEL_RG_CRYPTO }}
